basePath: /api
definitions:
  dtos.UserDto:
    properties:
      firstname:
        type: string
      lastname:
        type: string
    type: object
  infrastructure.Response:
    properties:
      data: {}
      errors:
        additionalProperties:
          type: string
        type: object
      message:
        type: string
      status:
        type: boolean
    type: object
  sign.LoginCommand:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
info:
  contact:
    email: ourworkemail@gmail.com
    name: We are united
    url: https://oursharedlink.com
  description: This is a social web server.
  title: Social API.
  version: "1.0"
paths:
  /sign:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/infrastructure.Response'
      summary: Allows the user to logout
      tags:
      - sign
    post:
      consumes:
      - application/json
      parameters:
      - description: Login object
        in: body
        name: LoginCommand
        required: true
        schema:
          $ref: '#/definitions/sign.LoginCommand'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/infrastructure.Response'
      summary: Allows the user to login
      tags:
      - sign
  /user/me:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.UserDto'
      summary: Represent information about current user
      tags:
      - user
swagger: "2.0"
