basePath: /api
definitions:
  app.Response:
    properties:
      data: {}
      errors: {}
      message:
        type: string
      status:
        type: boolean
    type: object
  dtos.UserDto:
    properties:
      firstname:
        type: string
      lastname:
        type: string
    type: object
  sign.LoginCommand:
    properties:
      age:
        minimum: 18
        type: integer
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  user.RegisterCommand:
    properties:
      firstname:
        type: string
      lastname:
        type: string
    required:
    - firstname
    - lastname
    type: object
info:
  contact:
    email: ourworkemail@gmail.com
    name: We are united
    url: https://oursharedlink.com
  description: This is a social web server.
  title: Social API.
  version: "1.0"
paths:
  /sign:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: Allows the user to logout
      tags:
      - sign
    post:
      consumes:
      - application/json
      parameters:
      - description: Login object
        in: body
        name: LoginCommand
        required: true
        schema:
          $ref: '#/definitions/sign.LoginCommand'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sign.LoginCommand'
      summary: Allows the user to login nonono
      tags:
      - sign
  /user:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.UserDto'
      summary: Represent information about current user
      tags:
      - user
    post:
      consumes:
      - application/json
      parameters:
      - description: Register object
        in: body
        name: RegisterCommand
        required: true
        schema:
          $ref: '#/definitions/user.RegisterCommand'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.RegisterCommand'
      summary: Allows user to register
      tags:
      - user
swagger: "2.0"
